<?php

$title="Test page 1";

require 'header.php';

?>

<p>This is a test page.  If logged in, we will be here I guess. This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. </p>
<p>This is a test page.  If logged in, we will be here I guess. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. </p>
<p>This is a test page.  If logged in, we will be here I guess. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. </p>
<p>This is a test page.  If logged in, we will be here I guess. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. </p>
<p>This is a test page.  If logged in, we will be here I guess. This is some text. This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. </p>
<p>This is a test page.  If logged in, we will be here I guess. This is some text. This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text.This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. </p>
<a href="test2.php">Link to next page, test next session</a>

<?php
require 'footer.php';
?>